name: klontong_kodeaqua
description: "A small convenience store wants to enter the 21st century by selling their products online."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cancellation_token: ^2.0.1
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  flutter_bcrypt: ^1.0.8
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
